Repository SpongePowered/Sponge, pull requests merged in 2018-02, with the labels that each got.

#1787 Fix: Client Crash with MixinExplosion as cause.
  src/main/java/org/spongepowered/common/mixin/core/world/MixinExplosion.java
Labels: type: bug

#1783 Fix InteractEntityEvent interaction point not always being absolute
  src/main/java/org/spongepowered/common/mixin/core/network/MixinNetHandlerPlayServer.java
Labels: status: needs review, status: needs testing

#1789 Make MixinItemMap methods respect client side more
  src/main/java/org/spongepowered/common/mixin/core/item/MixinItemMap.java
Labels: status: needs review, status: needs testing, system: client, type: bug

#1790 Fix saplings (and apples) not dropping from decaying leaves
  src/main/java/org/spongepowered/common/event/tracking/phase/block/BlockDecayPhaseState.java
Labels: status: needs review, status: needs testing

#1803 Config Comment Cleanup
  src/main/java/org/spongepowered/common/config/category/AsyncLightingCategory.java
  src/main/java/org/spongepowered/common/config/category/BlockCapturingCategory.java
  src/main/java/org/spongepowered/common/config/category/BlockCapturingModCategory.java
  src/main/java/org/spongepowered/common/config/category/BlockTrackingCategory.java
  src/main/java/org/spongepowered/common/config/category/BungeeCordCategory.java
  src/main/java/org/spongepowered/common/config/category/CollisionModCategory.java
  src/main/java/org/spongepowered/common/config/category/CommandsCategory.java
  src/main/java/org/spongepowered/common/config/category/CustomDataRegistrationCategory.java
  src/main/java/org/spongepowered/common/config/category/DebugCategory.java
  src/main/java/org/spongepowered/common/config/category/EntityActivationModCategory.java
  src/main/java/org/spongepowered/common/config/category/EntityActivationRangeCategory.java
  src/main/java/org/spongepowered/common/config/category/EntityCategory.java
  src/main/java/org/spongepowered/common/config/category/EntityCollisionCategory.java
  src/main/java/org/spongepowered/common/config/category/ExploitCategory.java
  src/main/java/org/spongepowered/common/config/category/GeneralCategory.java
  src/main/java/org/spongepowered/common/config/category/GlobalGeneralCategory.java
  src/main/java/org/spongepowered/common/config/category/GlobalWorldCategory.java
  src/main/java/org/spongepowered/common/config/category/ModuleCategory.java
  src/main/java/org/spongepowered/common/config/category/OptimizationCategory.java
  src/main/java/org/spongepowered/common/config/category/PhaseTrackerCategory.java
  src/main/java/org/spongepowered/common/config/category/StructureModCategory.java
  src/main/java/org/spongepowered/common/config/category/StructureSaveCategory.java
  src/main/java/org/spongepowered/common/config/category/TeleportHelperCategory.java
  src/main/java/org/spongepowered/common/config/category/TileEntityActivationCategory.java
  src/main/java/org/spongepowered/common/config/category/TileEntityActivationModCategory.java
  src/main/java/org/spongepowered/common/config/category/WorldCategory.java
  src/main/java/org/spongepowered/common/config/type/GeneralConfigBase.java
  src/main/java/org/spongepowered/common/mixin/plugin/GameFixPlugin.java
Labels: status: input wanted, status: needs review, type: enhancement

#1757 Fix empty block owner after falling
  src/main/java/org/spongepowered/common/event/tracking/phase/packet/PacketState.java
  src/main/java/org/spongepowered/common/event/tracking/phase/tick/BlockEventTickPhaseState.java
Labels: status: needs review, status: needs testing, system: phase tracker, version: 1.12

#1808 Move Block Break Logic handling to after ChangeBlockEvents
  src/main/java/org/spongepowered/common/event/tracking/TrackingUtil.java
  src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java
Labels: priority: high, status: needs review, status: needs testing, system: event, system: phase tracker, type: bug, version: 1.12
