Repository SpongePowered/Sponge, pull requests merged in 2019-08, with the labels that each got.

#2302 Fix/user sync
  src/main/java/org/spongepowered/common/entity/player/SpongeUser.java
  src/main/java/org/spongepowered/common/mixin/api/data/DataHolderMixin_API.java
  src/main/java/org/spongepowered/common/mixin/core/server/PlayerListMixin.java
  src/main/java/org/spongepowered/common/service/user/UserDiscoverer.java
  src/main/java/org/spongepowered/common/util/NetworkUtil.java
Labels: status: needs review, status: needs testing, type: bug

#2300 Introduce Metrics Collection States
  src/main/java/org/spongepowered/common/command/SpongeCommandFactory.java
  src/main/java/org/spongepowered/common/config/category/MetricsCategory.java
  src/main/java/org/spongepowered/common/util/SpongeHooks.java
  src/main/java/org/spongepowered/common/util/metric/SpongeMetricsConfigManager.java
Labels: status: needs review, status: needs testing

#2330 Fix scaled health
  src/main/java/org/spongepowered/common/bridge/entity/player/ServerPlayerEntityBridge.java
  src/main/java/org/spongepowered/common/data/processor/data/entity/HealthScalingProcessor.java
  src/main/java/org/spongepowered/common/mixin/core/entity/EntityTrackerEntryMixin.java
  src/main/java/org/spongepowered/common/mixin/core/entity/player/EntityPlayerMPMixin.java
  src/main/java/org/spongepowered/common/util/Constants.java
Labels: status: needs review, status: needs testing, type: bug

#2336 Fix server icons.
  src/main/java/org/spongepowered/common/mixin/api/mcp/network/ServerStatusResponseMixin_API.java
  src/main/java/org/spongepowered/common/mixin/core/network/ServerStatusResponseMixin.java
Labels: status: needs review, status: needs testing, type: bug

#2341 Automatically infer next entity to spawn - Closes #1864
  src/main/java/org/spongepowered/common/data/processor/value/SpawnerEntitiesValueProcessor.java
Labels: type: enhancement
