Repository SpongePowered/Sponge, pull requests merged in 2019-02, with the labels that each got.

#1296 Add some helper methods for working with ServerBossBars
  src/main/java/org/spongepowered/common/mixin/core/entity/boss/MixinEntityDragon.java
  src/main/java/org/spongepowered/common/mixin/core/entity/boss/MixinEntityWither.java
  src/main/java/org/spongepowered/common/mixin/core/world/MixinBossInfoServer.java
  src/main/resources/META-INF/common_at.cfg
Labels: status: needs review, status: needs testing, type: enhancement

#1368 Don't convert back and forth between Explosion objects and their unpacked data.
  src/main/java/org/spongepowered/common/interfaces/entity/explosive/IMixinExplosive.java
  src/main/java/org/spongepowered/common/interfaces/world/IMixinWorldServer.java
  src/main/java/org/spongepowered/common/mixin/core/world/MixinWorld.java
  src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java
  src/main/java/org/spongepowered/common/mixin/optimization/MixinWorldServer_Explosion.java
  src/main/java/org/spongepowered/common/mixin/optimization/explosion/IMixinExplosion.java
  src/main/java/org/spongepowered/common/world/SpongeExplosionBuilder.java
Labels: status: needs review, status: needs testing, system: event, system: phase tracker, type: bug

#1599 Add test plugin WitherSpawnTest
  testplugins/src/main/java/org/spongepowered/test/WitherSpawnTest.java
Labels: status: needs review, status: needs testing, system: test

#1888 Move the SimpleServiceManager to impl.
  src/main/java/org/spongepowered/common/inject/SpongeImplementationModule.java
  src/main/java/org/spongepowered/common/service/SpongeServiceManager.java
  src/main/java/org/spongepowered/common/service/package-info.java
  src/test/java/org/spongepowered/common/service/SpongeServiceManagerTest.java
  src/test/java/org/spongepowered/common/util/test/TestHooks.java
Labels: branch: bleeding, status: ready to merge

#2181 Fix missing EventContextKeys during Interact events
  src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
  src/main/java/org/spongepowered/common/mixin/core/server/MixinMinecraftServer.java
Labels: status: needs review, status: needs testing, type: enhancement

#2026 SpongeEntityType invalid cast fix
  src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
Labels: status: needs review, status: needs testing, type: bug

#1032 EnderDragon phases
  src/main/java/org/spongepowered/common/mixin/core/entity/boss/MixinEntityDragon.java
  src/main/java/org/spongepowered/common/mixin/core/entity/boss/dragon/phase/MixinIPhase.java
  src/main/java/org/spongepowered/common/mixin/core/entity/boss/dragon/phase/MixinPhaseList.java
  src/main/java/org/spongepowered/common/mixin/core/entity/boss/dragon/phase/MixinPhaseManager.java
  src/main/java/org/spongepowered/common/registry/CommonModuleRegistry.java
  src/main/java/org/spongepowered/common/registry/type/entity/EnderDragonPhaseTypeRegistryModule.java
  src/main/resources/META-INF/common_at.cfg
  src/main/resources/mixins.common.core.json
Labels: status: needs review, status: needs testing, type: enhancement

#2095 Compatibility Layer fix for ForgeMultiPart
  src/main/java/org/spongepowered/common/SpongeImplHooks.java
  src/main/java/org/spongepowered/common/mixin/core/tileentity/MixinTileEntity.java
  src/main/java/org/spongepowered/common/registry/type/block/TileEntityTypeRegistryModule.java
Labels: status: needs review, status: needs testing, type: bug

#2145 Allow modify item MaxStackSize more then 64
  src/main/java/org/spongepowered/common/mixin/core/network/MixinNetHandlerPlayServer.java
Labels: status: needs review, status: needs testing

#2165 Prevent having to use "minecraft:" when getting particle types
  src/main/java/org/spongepowered/common/registry/CommonModuleRegistry.java
  src/main/java/org/spongepowered/common/registry/type/effect/ParticleTypeRegistryModule.java
Labels: status: needs review, status: needs testing, type: bug

#2127 Fix missing manipulators
  src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntityMinecartCommandBlock.java
  src/main/java/org/spongepowered/common/mixin/core/entity/projectile/MixinEntityArrow.java
Labels: status: needs review, status: needs testing, type: bug

#2186 Make sure lens don't throw errors when a container minecart with empt…
  src/main/java/org/spongepowered/common/item/inventory/lens/impl/DefaultEmptyLens.java
  src/main/java/org/spongepowered/common/mixin/core/entity/item/MixinEntityMinecartContainer.java
Labels: status: needs review, status: needs testing, type: bug

#2189 Close the level_sponge I/O streams earlier.
  src/main/java/org/spongepowered/common/mixin/core/world/storage/MixinSaveHandler.java
Labels: status: needs review, status: needs testing, system: world, type: enhancement, version: 1.12
