Repository SpongePowered/Sponge, pull requests merged in 2019-11, with the labels that each got.

#2405 Fix duplicate InteractItemEvent.Secondary
  src/main/java/org/spongepowered/common/mixin/core/network/NetHandlerPlayServerMixin.java
Labels: status: needs review, status: needs testing, system: event, type: bug

#2406 Wait for the previous occurrence of the task to terminate
  src/main/java/org/spongepowered/common/scheduler/ScheduledTask.java
  src/main/java/org/spongepowered/common/scheduler/SchedulerBase.java
Labels: status: needs review, status: needs testing, type: bug, version: 1.12

#2407 Fix PickupDelayData and DespawnDelayData
  src/main/java/org/spongepowered/common/data/manipulator/immutable/entity/ImmutableSpongeDespawnDelayData.java
  src/main/java/org/spongepowered/common/data/manipulator/immutable/entity/ImmutableSpongePickupDelayData.java
  src/main/java/org/spongepowered/common/data/manipulator/mutable/entity/SpongeDespawnDelayData.java
  src/main/java/org/spongepowered/common/data/manipulator/mutable/entity/SpongePickupDelayData.java
Labels: status: needs review, status: needs testing, type: bug

#2408 Fix exceptions when using FusedExplosive methods
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityTNTPrimedMixin_API.java
  src/main/java/org/spongepowered/common/mixin/core/entity/item/EntityTNTPrimedMixin.java
  testplugins/src/main/java/org/spongepowered/test/DefuseExplosiveTest.java
Labels: status: needs review, status: needs testing, type: bug

#2399 Migrate several patches to SV since they're now in Forge proper.
  src/main/java/org/spongepowered/common/mixin/exploit/ChunkMixin_AssuredChangesMarkedDirty.java
  src/main/java/org/spongepowered/common/mixin/exploit/EntityLeashKnotMixin_ProcessChunkOnMove.java
  src/main/java/org/spongepowered/common/mixin/exploit/EntityMixin_ChunkLoadOnPositionSet.java
  src/main/java/org/spongepowered/common/mixin/exploit/EntityMixin_ProcessChunkOnMove.java
  src/main/java/org/spongepowered/common/mixin/exploit/EntityShulkerMixin_ProcessChunkOnMove.java
  src/main/java/org/spongepowered/common/mixin/exploit/NetHandlerPlayServerMixin_LimitBookSize.java
  src/main/java/org/spongepowered/common/mixin/exploit/NetHandlerPlayServerMixin_PlayerVehiclesSyncPatch.java
  src/main/resources/mixins.common.exploit.json
Labels: status: input wanted, status: needs review

#2409 Do not allow for CatalogType#getId in mixin classes to be overridden
  src/main/java/org/spongepowered/common/mixin/api/mcp/advancements/AdvancementMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/block/BlockMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/enchantment/EnchantmentMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/item/ItemMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/world/biome/BiomeMixin_API.java
Labels: status: needs review, status: needs testing, type: enhancement

#2389 Implement TeleporterMixin.bridge$placeEntity for SpongeVanilla.
  src/main/java/org/spongepowered/common/event/tracking/IPhaseState.java
  src/main/java/org/spongepowered/common/event/tracking/phase/entity/InvokingTeleporterState.java
  src/main/java/org/spongepowered/common/mixin/core/world/TeleporterMixin.java
  src/main/java/org/spongepowered/common/util/Constants.java
Labels: status: needs review, status: needs testing, version: 1.12

#2420 Replace PlayerKickHelper with NetHandlerPlayServer.disconnect().
  src/main/java/org/spongepowered/common/entity/player/PlayerKickHelper.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/player/EntityPlayerMPMixin_API.java
Labels: priority: low, status: needs review, system: network

#2422 Use level_sponge.dat.old when unable to read level_sponge.dat
  src/main/java/org/spongepowered/common/mixin/core/world/storage/SaveHandlerMixin.java
Labels: status: needs review, version: 1.12
