Repository SpongePowered/Sponge, pull requests merged in 2019-03, with the labels that each got.

#2192 Fix instanceof check and safe cast to PortalAgent
  src/main/java/org/spongepowered/common/entity/EntityUtil.java
Labels: status: needs review, status: needs testing, type: bug

#2203 Fix missing CriteriaTriggers
  src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntityLivingBase.java
Labels: status: needs review, status: needs testing, type: bug

#2213 unmarkRemoval when adding a te and avoid closing a Proxy twice
  src/main/java/org/spongepowered/common/event/tracking/context/MultiBlockCaptureSupplier.java
  src/main/java/org/spongepowered/common/event/tracking/context/SpongeProxyBlockAccess.java
Labels: status: needs review, status: needs testing, type: bug

#2087 Implement API for Shulkers, ShulkerBullets and ShulkerBoxes
  src/main/java/org/spongepowered/common/data/DataRegistrar.java
  src/main/java/org/spongepowered/common/data/manipulator/immutable/entity/ImmutableSpongeTargetedEntityData.java
  src/main/java/org/spongepowered/common/data/manipulator/mutable/entity/SpongeTargetedEntityData.java
  src/main/java/org/spongepowered/common/data/processor/data/entity/EntityTargetedEntityDataProcessor.java
  src/main/java/org/spongepowered/common/data/processor/data/entity/ShulkerBulletDirectionalDataProcessor.java
  src/main/java/org/spongepowered/common/data/processor/data/entity/ShulkerDirectionalDataProcessor.java
  src/main/java/org/spongepowered/common/data/processor/data/entity/ShulkerDyeColorDataProcessor.java
  src/main/java/org/spongepowered/common/data/util/DataConstants.java
  src/main/java/org/spongepowered/common/entity/projectile/ProjectileLauncher.java
  src/main/java/org/spongepowered/common/entity/projectile/ShulkerSourceLogic.java
  src/main/java/org/spongepowered/common/interfaces/IEntityTargetingEntity.java
  src/main/java/org/spongepowered/common/interfaces/entity/monster/IMixinShulker.java
  src/main/java/org/spongepowered/common/interfaces/entity/projectile/IMixinShulkerBullet.java
  src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntityShulkerBullet.java
  src/main/java/org/spongepowered/common/mixin/core/entity/monster/MixinEntityShulker.java
  src/main/java/org/spongepowered/common/mixin/core/tileentity/MixinTileEntityShulkerBox.java
  src/main/java/org/spongepowered/common/registry/type/data/KeyRegistryModule.java
  testplugins/src/main/java/org/spongepowered/test/ShulkerTest.java
Labels: status: needs review, status: needs testing, type: enhancement

#1914 Implement missing damage sources and types
  src/main/java/org/spongepowered/common/registry/provider/DamageSourceToTypeProvider.java
  src/main/java/org/spongepowered/common/registry/type/event/DamageSourceRegistryModule.java
Labels: status: needs review, system: event

#2167 Add RegistryModule test plugin
  testplugins/src/main/java/org/spongepowered/test/myranks/MyRanks.java
  testplugins/src/main/java/org/spongepowered/test/myranks/RankImpl.java
  testplugins/src/main/java/org/spongepowered/test/myranks/RankRegistryModule.java
  testplugins/src/main/java/org/spongepowered/test/myranks/api/Keys.java
  testplugins/src/main/java/org/spongepowered/test/myranks/api/Rank.java
  testplugins/src/main/java/org/spongepowered/test/myranks/api/Ranks.java
Labels: status: needs review, status: needs testing, system: test

#2220 Misc fixes for EntitySnapshot
  src/main/java/org/spongepowered/common/data/manipulator/mutable/entity/SpongeTargetedEntityData.java
  src/main/java/org/spongepowered/common/entity/SpongeEntitySnapshot.java
  src/main/java/org/spongepowered/common/entity/SpongeEntitySnapshotBuilder.java
  src/test/java/org/spongepowered/common/data/manipulator/ManipulatorTest.java
Labels: status: needs review, status: needs testing

#2215 Fix dimension ids duplication
  src/main/java/org/spongepowered/common/data/util/NbtDataUtil.java
  src/main/java/org/spongepowered/common/world/WorldManager.java
Labels: status: needs review, status: needs testing, type: bug

#2229 Fix Neighbor block updates in production environment
  src/main/java/org/spongepowered/common/mixin/core/block/MixinBlock.java
Labels: status: needs review, status: needs testing, type: bug
