Repository SpongePowered/Sponge, pull requests merged in 2019-01, with the labels that each got.

#2171 Let JVM figure out size of BlockTrait array
  src/main/java/org/spongepowered/common/block/SpongeBlockStateMatcherBuilder.java
Labels: status: ready to merge

#2125 Standardize interact events
  src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
  src/main/java/org/spongepowered/common/event/tracking/phase/packet/PacketContext.java
  src/main/java/org/spongepowered/common/mixin/core/network/MixinNetHandlerPlayServer.java
  src/main/java/org/spongepowered/common/mixin/core/server/MixinMinecraftServer.java
  src/main/java/org/spongepowered/common/mixin/core/server/management/MixinPlayerInteractionManager.java
Labels: status: needs review, status: needs testing, type: bug

#2119 Fix spectator not working on respawn
  src/main/java/org/spongepowered/common/mixin/core/server/MixinPlayerList.java
  testplugins/src/main/java/org/spongepowered/test/RespawnSpectatorTest.java
Labels: status: needs review, status: needs testing, type: bug

#1429 Add Test Plugin : Score Text Test
  testplugins/src/main/java/org/spongepowered/test/SelectorTextTest.java
Labels: status: ready to merge, system: test
