Repository SpongePowered/Sponge, pull requests merged in 2019-06, with the labels that each got.

#2274 Implement DisabledSlotsData for Armor Stands
  src/main/java/org/spongepowered/common/data/DataRegistrar.java
  src/main/java/org/spongepowered/common/data/manipulator/immutable/entity/ImmutableSpongeDisabledSlotsData.java
  src/main/java/org/spongepowered/common/data/manipulator/mutable/entity/SpongeDisabledSlotsData.java
  src/main/java/org/spongepowered/common/data/processor/multi/entity/DisabledSlotsDataProcessor.java
  src/main/java/org/spongepowered/common/data/processor/value/entity/PlacingDisabledValueProcessor.java
  src/main/java/org/spongepowered/common/data/processor/value/entity/TakingDisabledValueProcessor.java
  src/main/java/org/spongepowered/common/mixin/core/entity/item/MixinEntityArmorStand.java
  src/main/java/org/spongepowered/common/registry/type/data/KeyRegistryModule.java
  src/main/resources/META-INF/common_at.cfg
Labels: status: needs review, status: needs testing, system: data

#2286 Clean up SpongePlayerDataHandler.saveFile().
  src/main/java/org/spongepowered/common/world/storage/SpongePlayerDataHandler.java
Labels: status: needs review, status: needs testing, type: enhancement

#2285 Fix/registrymodule registration
  src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java
Labels: status: needs review, status: needs testing

#2295 Change SchematicUpgradeTest to not use File
  src/test/java/org/spongepowered/common/regression/SchematicUpgradeTest.java
Labels: status: needs review, status: needs testing

#2297 Cleanup/config
  src/main/java/org/spongepowered/common/config/category/DebugCategory.java
  src/main/java/org/spongepowered/common/config/category/EntityCategory.java
  src/main/java/org/spongepowered/common/config/category/EntityCollisionCategory.java
  src/main/java/org/spongepowered/common/config/category/GeneralCategory.java
  src/main/java/org/spongepowered/common/config/category/GlobalWorldCategory.java
  src/main/java/org/spongepowered/common/config/category/WorldCategory.java
Labels: status: needs review, status: needs testing, type: enhancement

#2296 Privacy-security/timings
  src/main/java/org/spongepowered/common/config/category/TimingsCategory.java
  src/main/java/org/spongepowered/common/relocate/co/aikar/timings/SpongeTimingsFactory.java
  src/main/java/org/spongepowered/common/relocate/co/aikar/timings/TimingsExport.java
Labels: status: needs review, status: needs testing

#2299 Add minor async lighting improvements
  src/main/java/org/spongepowered/common/bridge/world/chunk/ChunkBridge.java
  src/main/java/org/spongepowered/common/mixin/optimization/world/MixinChunk_Async_Lighting.java
  src/main/java/org/spongepowered/common/mixin/optimization/world/MixinWorldServer_Async_Lighting.java
Labels: status: needs review, status: needs testing, type: enhancement
