Repository SpongePowered/Sponge, pull requests merged in 2020-02, with the labels that each got.

#2496 Casting a very big shadow (API Mixins) (1.14)
  src/main/java/org/spongepowered/common/mixin/api/common/event/cause/block/damage/MinecraftFallingBlockDamageSourceMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/advancements/CriterionProgressMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/advancements/DisplayInfoMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/enchantment/EnchantmentMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/EntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/LivingEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/boss/dragon/phase/PhaseManagerMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EnderCrystalEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/FireworkRocketEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/TNTEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/minecart/TNTMinecartEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/merchant/villager/AbstractVillagerEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/monster/CreeperEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/ParrotEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/horse/LlamaEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/player/PlayerEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/projectile/FireballEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/projectile/WitherSkullEntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/item/ItemMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/item/ItemStackMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/network/PacketBufferMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/network/play/ServerPlayNetHandlerMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/potion/EffectInstanceMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/scoreboard/ScorePlayerTeamMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/scoreboard/ServerScoreboardMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/server/management/PlayerProfileCacheMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/server/management/ProfileBanEntryMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/server/management/UserListEntryMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/util/CooldownTrackerMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/util/DamageSourceMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/util/SoundEventMixin_API.java
  src/main/java/org/spongepowered/common/raid/SpongeWave.java
Labels: status: needs review, version: 1.14

#2489 Remove Queries.WORLD_NAME costrain from location builder
  src/main/java/org/spongepowered/common/data/builder/world/LocationBuilder.java
Labels: status: needs review, status: needs testing, version: 1.12

#2504 Fix EntityHit distance calculation
  src/main/java/org/spongepowered/common/mixin/api/mcp/world/WorldMixin_API.java
Labels: status: ready to merge

#2469 Invoke command on main thread if it is invoked from off-thread
  src/main/java/org/spongepowered/common/command/SpongeCommandManager.java
  testplugins/src/main/java/org/spongepowered/test/CommandTestPlugin.java
Labels: priority: low, status: needs review, system: command, version: 1.12

#2510 Throw more meaningful exception if an invalid block state ID is required
  src/main/java/org/spongepowered/common/registry/type/BlockStateRegistryModule.java
Labels: status: input wanted

#2492 Fix ClassCastException in ValueProcessorDelegate#offerToStore() method
  src/main/java/org/spongepowered/common/data/util/ValueProcessorDelegate.java
Labels: status: requested changes, type: bug, version: 1.12
