Repository SpongePowered/Sponge, pull requests merged in 2020-12, with the labels that each got.

#3220 Include space in log entries
  vanilla/src/applaunch/resources/log4j2.xml
  vanilla/src/installer/resources/log4j2_launcher.xml
Labels: version: 1.15

#3206 Add max-chunk-lifetime setting used by chunk gc (#3167) - fixed
  src/main/java/org/spongepowered/common/bridge/world/chunk/ChunkBridge.java
  src/main/java/org/spongepowered/common/config/category/WorldCategory.java
  src/main/java/org/spongepowered/common/mixin/core/world/chunk/ChunkMixin.java
  src/main/java/org/spongepowered/common/mixin/core/world/gen/ChunkProviderServerMixin.java
  src/main/java/org/spongepowered/common/util/Constants.java
Labels: version: 1.12

#3204 Fix MC-49577 re-introduced by MixinWorldEntitySpawner.findChunksForSpawning refactor
  src/main/java/org/spongepowered/common/mixin/core/world/WorldEntitySpawnerMixin.java
Labels: type: bug, version: 1.12

#3224 Fix typos in config docs
  src/main/java/org/spongepowered/common/config/category/EntityCollisionCategory.java
  src/main/java/org/spongepowered/common/config/category/ExploitCategory.java
  src/main/java/org/spongepowered/common/config/category/MetricsCategory.java
  src/main/java/org/spongepowered/common/config/category/OptimizationCategory.java
  src/main/java/org/spongepowered/common/config/category/StructureModCategory.java
  src/main/java/org/spongepowered/common/config/category/StructureSaveCategory.java
  src/main/java/org/spongepowered/common/config/category/TimingsCategory.java
Labels: version: 1.12
