Repository SpongePowered/Sponge, pull requests merged in 2020-01, with the labels that each got.

#2461 Change impl$callSignChangeEvent to a Redirect to support SV upgrade to 0.8
  src/main/java/org/spongepowered/common/mixin/core/network/NetHandlerPlayServerMixin.java
Labels: status: needs review

#2460 Fix custom data not persisting across respawns
  src/main/java/org/spongepowered/common/mixin/core/server/PlayerListMixin.java
Labels: status: needs review, status: needs testing, type: bug

#2483 Fix Async tasks stalling
  src/main/java/org/spongepowered/common/scheduler/AsyncScheduler.java
  src/main/java/org/spongepowered/common/scheduler/ScheduledTask.java
  testplugins/src/main/java/org/spongepowered/test/AsyncSchedulerTest.java
Labels: status: needs testing

#2486 Register and implement TropicalFishShape
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/fish/TropicalFishEntityMixin_TypeMixin_API.java
  src/main/java/org/spongepowered/common/registry/SpongeCatalogRegistry.java
  src/main/resources/META-INF/common_at.cfg
  src/main/resources/mixins.common.api.json
Labels: status: needs review, version: 1.14
