Repository SpongePowered/Sponge, pull requests merged in 2020-07, with the labels that each got.

#3032 Update readme for FG3
  README.md
Labels: version: 1.14

#3043 Return true when Forge short circuits a damage entity calculation
  src/main/java/org/spongepowered/common/mixin/core/entity/EntityLivingBaseMixin.java
Labels: system: event, type: bug, version: 1.12

#2523 Add support of offering ConnectedDirectionsData for some block states
  src/main/java/org/spongepowered/common/mixin/core/block/BlockFenceMixin.java
  src/main/java/org/spongepowered/common/mixin/core/block/BlockPaneMixin.java
  src/main/java/org/spongepowered/common/mixin/core/block/BlockRedstoneWireMixin.java
  src/main/java/org/spongepowered/common/mixin/core/block/BlockTripWireMixin.java
  src/main/java/org/spongepowered/common/mixin/core/block/BlockVineMixin.java
  src/main/java/org/spongepowered/common/mixin/core/block/BlockWallMixin.java
  src/main/java/org/spongepowered/common/util/Constants.java
Labels: status: needs review, status: needs testing, system: data

#3071 Fix client completion when a parameter is not optional but reads nothing
  src/main/java/org/spongepowered/common/command/SpongeParameterizedCommand.java
  src/main/java/org/spongepowered/common/command/brigadier/SpongeParameterTranslator.java
  src/main/java/org/spongepowered/common/command/brigadier/SpongeStringReader.java
  src/main/java/org/spongepowered/common/command/brigadier/TranslatedParameter.java
  src/main/java/org/spongepowered/common/command/brigadier/argument/AbstractArgumentParser.java
  src/main/java/org/spongepowered/common/command/brigadier/argument/ArgumentParser.java
  src/main/java/org/spongepowered/common/command/brigadier/argument/CustomArgumentParser.java
  src/main/java/org/spongepowered/common/command/brigadier/argument/StandardArgumentParser.java
  src/main/java/org/spongepowered/common/command/brigadier/context/SpongeCommandContextBuilder.java
  src/main/java/org/spongepowered/common/command/brigadier/dispatcher/SpongeCommandDispatcher.java
  src/main/java/org/spongepowered/common/command/brigadier/tree/SpongeArgumentCommandNode.java
  src/main/java/org/spongepowered/common/command/brigadier/tree/SpongeArgumentCommandNodeBuilder.java
  src/main/java/org/spongepowered/common/command/brigadier/tree/SpongeLiteralCommandNode.java
  src/main/java/org/spongepowered/common/command/brigadier/tree/SpongeNode.java
  src/main/java/org/spongepowered/common/command/brigadier/tree/SpongeRootCommandNode.java
  src/main/java/org/spongepowered/common/command/brigadier/tree/UnsortedNodeHolder.java
  src/main/java/org/spongepowered/common/command/parameter/SpongeDefaultValueParser.java
  src/main/java/org/spongepowered/common/command/parameter/SpongeParameterValue.java
  src/main/java/org/spongepowered/common/command/parameter/SpongeParameterValueBuilder.java
  src/main/java/org/spongepowered/common/command/parameter/managed/standard/SpongeWorldPropertiesValueParameter.java
  src/main/java/org/spongepowered/common/util/Constants.java
  src/mixins/java/org/spongepowered/common/mixin/core/command/CommandsMixin.java
Labels: system: command, version: 1.14

#3085 Serialize schematic dims as shorts
  src/main/java/org/spongepowered/common/data/persistence/SchematicTranslator.java
Labels: type: bug, version: 1.12

#3088 Fix TileEntity/EntityActivation range
  src/main/java/org/spongepowered/common/mixin/plugin/entityactivation/EntityActivationRange.java
  src/main/java/org/spongepowered/common/mixin/plugin/tileentityactivation/TileEntityActivation.java
Labels: type: bug, version: 1.12

#3087 Add config option to disable neighbor notification to unloaded chunks
  src/main/java/org/spongepowered/common/bridge/world/WorldServerBridge.java
  src/main/java/org/spongepowered/common/config/category/WorldCategory.java
  src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
  src/main/java/org/spongepowered/common/mixin/core/world/WorldMixin.java
  src/main/java/org/spongepowered/common/mixin/core/world/WorldServerMixin.java
Labels: type: enhancement, version: 1.12

#2506 Replace craft preview transaction list with a single entry.
  src/main/java/org/spongepowered/common/bridge/inventory/ContainerBridge.java
  src/main/java/org/spongepowered/common/config/category/LoggingCategory.java
  src/main/java/org/spongepowered/common/event/tracking/phase/packet/drag/DragInventoryStopState.java
  src/main/java/org/spongepowered/common/event/tracking/phase/packet/inventory/InventoryPacketContext.java
  src/main/java/org/spongepowered/common/event/tracking/phase/packet/inventory/PlaceRecipePacketState.java
  src/main/java/org/spongepowered/common/item/inventory/adapter/impl/slots/SlotAdapter.java
  src/main/java/org/spongepowered/common/mixin/core/inventory/ContainerMixin.java
  src/main/java/org/spongepowered/common/mixin/core/inventory/SlotCraftingMixin.java
Labels: status: needs review, status: needs testing, system: inventory, version: 1.12

#2636 Inline micro optimize some bits in MultiBlockCaptureSupplier
  src/main/java/org/spongepowered/common/event/tracking/context/MultiBlockCaptureSupplier.java
Labels: type: performance, version: 1.12
