Repository SpongePowered/Sponge, pull requests merged in 2020-08, with the labels that each got.

#3116 Fix NPE when trying to sleep
  src/mixins/java/org/spongepowered/common/mixin/core/entity/LivingEntityMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/entity/player/PlayerEntityMixin.java
Labels: type: bug, version: 1.15

#3044 Update pagination service from invalid
  build.gradle.kts
  invalid/main/java/org/spongepowered/common/service/pagination/SpongePaginationService.java
  src/main/java/org/spongepowered/common/command/manager/SpongeCommandManager.java
  src/main/java/org/spongepowered/common/service/SpongeServiceProvider.java
  src/main/java/org/spongepowered/common/service/pagination/ActivePagination.java
  src/main/java/org/spongepowered/common/service/pagination/IterablePagination.java
  src/main/java/org/spongepowered/common/service/pagination/ListPagination.java
  src/main/java/org/spongepowered/common/service/pagination/PaginationCalculator.java
  src/main/java/org/spongepowered/common/service/pagination/SpongePaginationBuilder.java
  src/main/java/org/spongepowered/common/service/pagination/SpongePaginationList.java
  src/main/java/org/spongepowered/common/service/pagination/SpongePaginationService.java
Labels: version: 1.14

#3127 Remove EnchantmentHelper leak patch
  invalid/main/java/org/spongepowered/common/mixin/invalid/optimization/mcp/enchantment/EnchantmentHelperMixin_Optimization_No_Source_Leak.java
  src/applaunch/java/org/spongepowered/common/applaunch/config/common/OptimizationCategory.java
  src/mixins/java/org/spongepowered/common/mixin/plugin/OptimizationPlugin.java
Labels: version: 1.14

#3125 Drop file injection support
  src/main/java/org/spongepowered/common/inject/SpongeModule.java
  src/main/java/org/spongepowered/common/inject/provider/PathAsFileProvider.java
  src/main/java/org/spongepowered/common/inject/provider/PluginConfigurationModule.java
Labels: version: 1.14

#3124 Move ban classes to the ban package
  src/main/java/org/spongepowered/common/ban/SpongeBanBuilder.java
  src/main/java/org/spongepowered/common/ban/SpongeBanType.java
  src/main/java/org/spongepowered/common/registry/SpongeBuilderRegistry.java
  src/main/java/org/spongepowered/common/registry/SpongeCatalogRegistry.java
  src/main/java/org/spongepowered/common/registry/builtin/sponge/BanTypeStreamGenerator.java
  src/main/java/org/spongepowered/common/service/ban/SpongeBanService.java
  src/main/java/org/spongepowered/common/service/ban/SpongeIPBanList.java
  src/main/java/org/spongepowered/common/service/ban/SpongeUserListBans.java
  src/mixins/java/org/spongepowered/common/mixin/api/mcp/server/management/BanEntryMixin_API.java
  src/mixins/java/org/spongepowered/common/mixin/api/mcp/server/management/IPBanEntryMixin_API.java
  src/mixins/java/org/spongepowered/common/mixin/api/mcp/server/management/ProfileBanEntryMixin_API.java
Labels: version: 1.14

#3128 Remove unused config option for the old user storage service
  src/applaunch/java/org/spongepowered/common/applaunch/config/common/ServicesCategory.java
Labels: version: 1.14

#3129 Remove panda redstone
  invalid/main/java/org/spongepowered/common/mixin/invalid/optimization/mcp/block/RedstoneWireBlockMixin_Optimization_Panda.java
  src/applaunch/java/org/spongepowered/common/applaunch/config/common/OptimizationCategory.java
  src/mixins/java/org/spongepowered/common/mixin/plugin/OptimizationPlugin.java
Labels: version: 1.14

#3131 Change GameProfileManager method signature to return a map
  src/main/java/org/spongepowered/common/profile/SpongeGameProfileManager.java
  src/main/java/org/spongepowered/common/profile/query/NameQuery.java
  src/main/java/org/spongepowered/common/profile/query/Query.java
  src/main/java/org/spongepowered/common/profile/query/UniqueIdQuery.java
Labels: version: 1.14

#3132 Register sleep timer key
  src/accessors/java/org/spongepowered/common/accessor/entity/player/PlayerEntityAccessor.java
  src/main/java/org/spongepowered/common/data/provider/entity/PlayerData.java
Labels: version: 1.14

#3138 Add Audiences#withPermission
  src/main/java/org/spongepowered/common/adventure/AudienceFactory.java
Labels: version: 1.15

#3144 Implement the DataVersion accessor
  src/main/java/org/spongepowered/common/SpongeMinecraftVersion.java
  src/main/java/org/spongepowered/common/network/status/SpongeLegacyMinecraftVersion.java
  src/mixins/java/org/spongepowered/common/mixin/api/mcp/network/ServerStatusResponse_VersionMixin_API.java
Labels: version: 1.15

#3143 Implement BlockType#getStateProperties and BlockType#getStatePropertyByName
  src/mixins/java/org/spongepowered/common/mixin/api/mcp/block/BlockMixin_API.java
Labels: version: 1.15
