Repository SpongePowered/Sponge, pull requests merged in 2020-05, with the labels that each got.

#2587 Reduce SlotLensImpl allocation
  src/main/java/org/spongepowered/common/mixin/core/entity/EntityLivingBaseMixin.java
Labels: system: inventory, type: enhancement

#2591 Fix tileentitysign memory leak
  src/main/java/org/spongepowered/common/mixin/core/network/NetHandlerPlayServerMixin.java
Labels: version: 1.12

#2597 Avoid double key lookup in DataCompoundHolder#getSpongeCompound
  src/main/java/org/spongepowered/common/bridge/data/DataCompoundHolder.java
Labels: system: data, type: enhancement

#2600 Ensure default permissions are used with some wrapped subjects
  src/main/java/org/spongepowered/common/command/AndPermissionLevelSubject.java
  src/main/java/org/spongepowered/common/command/SpongeProxySource.java
Labels: system: permission, type: bug, version: 1.12

#2606 Fix SpawnEntityEvent not firing when applying entityarchetypes
  src/main/java/org/spongepowered/common/entity/SpongeEntityArchetype.java
Labels: system: event, version: 1.12

#2605 Init collision state lazily
  src/main/java/org/spongepowered/common/mixin/entitycollisions/ChunkMixin_Collisions.java
  src/main/java/org/spongepowered/common/mixin/entitycollisions/EntityMixin_Collisions.java
Labels: system: entity, type: performance, version: 1.12

#2595 Fix/invisibility processor
  src/main/java/org/spongepowered/common/data/processor/multi/entity/InvisibilityDataProcessor.java
  src/main/java/org/spongepowered/common/mixin/core/entity/player/EntityPlayerMixin.java
Labels: system: data, type: bug, version: 1.12

#2604 Improve runaway phase state detection
  src/main/java/org/spongepowered/common/event/tracking/PhaseStack.java
Labels: system: phase tracker, type: performance, version: 1.12

#2610 Init entity activation state lazily
  src/main/java/org/spongepowered/common/mixin/entityactivation/entity/EntityMixin_Activation.java
Labels: system: entity, type: performance, version: 1.12

#2607 Fix a few issues with shouldfires and use specific flags
  src/main/java/org/spongepowered/common/event/ShouldFire.java
  src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
  src/main/java/org/spongepowered/common/event/tracking/PhaseTracker.java
  src/main/java/org/spongepowered/common/mixin/core/entity/EntityMixin.java
  src/main/java/org/spongepowered/common/world/BlockChange.java
Labels: system: event, type: bug, type: enhancement, version: 1.12

#2612 Avoid Class#getCanonicalName call when creating a builder
  src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java
Labels: type: enhancement, version: 1.12

#2614 implement LaunchProjectileEvent
  src/main/java/org/spongepowered/common/entity/projectile/ProjectileLauncher.java
  src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
Labels: version: 1.12

#2613 Add totem effect to registry
  src/main/java/org/spongepowered/common/registry/type/effect/ParticleTypeRegistryModule.java
Labels: type: enhancement, type: impl request, version: 1.12

#2611 Reduce iterations in TileEntities activation
  src/main/java/org/spongepowered/common/mixin/plugin/tileentityactivation/TileEntityActivation.java
Labels: type: enhancement, type: performance, version: 1.12

#2618 Fix Forge LivingHurtEvent cancelling not being respected
  src/main/java/org/spongepowered/common/mixin/core/entity/EntityLivingBaseMixin.java
Labels: type: bug, version: 1.12

#2621 Add check on "level_sponge.dat" saving to make sure the output starts with 0x1F 0x8B
  src/main/java/org/spongepowered/common/config/category/GlobalGeneralCategory.java
  src/main/java/org/spongepowered/common/mixin/core/world/storage/SaveHandlerMixin.java
  src/main/java/org/spongepowered/common/util/Constants.java
Labels: status: input wanted

#2628 Don't mark Users as dirty when retrieving custom data
  src/main/java/org/spongepowered/common/mixin/api/data/DataHolderMixin_API.java
Labels: system: data, type: bug, type: enhancement, version: 1.12

#2620 API8 Fixing Data Impl
  invalid/main/java/org/spongepowered/common/data/DataProcessor.java
  invalid/main/java/org/spongepowered/common/data/DataRegistrar.java
  invalid/main/java/org/spongepowered/common/data/SpongeDataManager.java
  invalid/main/java/org/spongepowered/common/data/SpongeDataRegistration.java
  invalid/main/java/org/spongepowered/common/data/SpongeDataRegistrationBuilder.java
  invalid/main/java/org/spongepowered/common/data/SpongeManipulatorRegistry.java
  invalid/main/java/org/spongepowered/common/data/ValueProcessor.java
  invalid/main/java/org/spongepowered/common/data/util/DataProcessorDelegate.java
  invalid/main/java/org/spongepowered/common/data/util/DataUtil.java
  invalid/main/java/org/spongepowered/common/mixin/invalid/core/tileentity/TileEntityMixin.java
  src/main/java/org/spongepowered/common/bridge/data/CustomDataHolderBridge.java
  src/main/java/org/spongepowered/common/data/MemoryDataView.java
  src/main/java/org/spongepowered/common/data/SpongeDataManager.java
  src/main/java/org/spongepowered/common/data/SpongeDataRegistration.java
  src/main/java/org/spongepowered/common/data/SpongeDataRegistrationBuilder.java
  src/main/java/org/spongepowered/common/data/key/KeyBasedDataListener.java
  src/main/java/org/spongepowered/common/data/key/SpongeKey.java
  src/main/java/org/spongepowered/common/data/persistence/DataSerializers.java
  src/main/java/org/spongepowered/common/data/util/DataUtil.java
  src/main/java/org/spongepowered/common/data/util/LegacyCustomDataClassContentUpdater.java
  src/main/java/org/spongepowered/common/registry/CallbackRegistry.java
  src/main/java/org/spongepowered/common/registry/SpongeCatalogRegistry.java
  src/mixins/java/org/spongepowered/common/mixin/core/data/CustomDataHolderMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/entity/EntityMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/tileentity/TileEntityMixin.java
  src/mixins/resources/mixins.common.core.json
Labels: version: 1.14

#2569 Use Identity/Reference based collection where possible
  src/main/java/org/spongepowered/common/command/ChunkSaveHelper.java
  src/main/java/org/spongepowered/common/data/SpongeDataManager.java
  src/main/java/org/spongepowered/common/data/builder/block/tileentity/AbstractTileBuilder.java
  src/main/java/org/spongepowered/common/data/manipulator/immutable/common/AbstractImmutableData.java
  src/main/java/org/spongepowered/common/data/manipulator/mutable/common/AbstractData.java
  src/main/java/org/spongepowered/common/data/util/DataUtil.java
  src/main/java/org/spongepowered/common/entity/projectile/ProjectileLauncher.java
  src/main/java/org/spongepowered/common/event/ListenerChecker.java
  src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
  src/main/java/org/spongepowered/common/event/SpongeEventManager.java
  src/main/java/org/spongepowered/common/event/tracking/phase/packet/inventory/BasicInventoryPacketState.java
  src/main/java/org/spongepowered/common/item/inventory/SpongeInventoryBuilder.java
  src/main/java/org/spongepowered/common/item/inventory/archetype/SpongeInventoryArchetypeBuilder.java
  src/main/java/org/spongepowered/common/item/inventory/fabric/InventoryTranslators.java
  src/main/java/org/spongepowered/common/item/inventory/lens/impl/ReusableLens.java
  src/main/java/org/spongepowered/common/item/recipe/smelting/CustomSmeltingRecipeIds.java
  src/main/java/org/spongepowered/common/mixin/core/block/BlockFenceMixin.java
  src/main/java/org/spongepowered/common/mixin/core/block/BlockPaneMixin.java
  src/main/java/org/spongepowered/common/mixin/core/block/BlockRedstoneWireMixin.java
  src/main/java/org/spongepowered/common/mixin/core/block/BlockTripWireMixin.java
  src/main/java/org/spongepowered/common/mixin/core/block/BlockVineMixin.java
  src/main/java/org/spongepowered/common/mixin/core/block/BlockWallMixin.java
  src/main/java/org/spongepowered/common/mixin/core/inventory/ContainerMixin.java
  src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java
  src/main/java/org/spongepowered/common/registry/provider/DirectionFacingProvider.java
  src/main/java/org/spongepowered/common/registry/type/data/DataTranslatorRegistryModule.java
  src/main/java/org/spongepowered/common/registry/type/entity/EntityTypeRegistryModule.java
  src/main/java/org/spongepowered/common/registry/type/entity/HorseColorRegistryModule.java
  src/main/java/org/spongepowered/common/registry/type/entity/HorseStyleRegistryModule.java
  src/main/java/org/spongepowered/common/registry/type/entity/OcelotTypeRegistryModule.java
  src/main/java/org/spongepowered/common/registry/type/entity/ParrotVariantRegistryModule.java
  src/main/java/org/spongepowered/common/registry/type/entity/RabbitTypeRegistryModule.java
  src/main/java/org/spongepowered/common/registry/type/world/PortalAgentRegistryModule.java
  src/main/java/org/spongepowered/common/registry/type/world/gen/PopulatorTypeRegistryModule.java
  src/main/java/org/spongepowered/common/util/TristateUtil.java
  src/main/java/org/spongepowered/common/world/VirtualPortalAgent.java
  src/main/java/org/spongepowered/common/world/WorldManager.java
Labels: type: performance, version: 1.12
