Repository SpongePowered/Sponge, pull requests merged in 2020-06, with the labels that each got.

#2626 Log chunk load queue
  src/main/java/org/spongepowered/common/util/SpongeHooks.java
Labels: type: enhancement, version: 1.12

#2641 Fix UserListEntryBan memory leak
  src/main/java/org/spongepowered/common/mixin/core/server/management/UserListEntryBanMixin.java
Labels: version: 1.12

#2643 Fix ChunkRegenerateFlagRegistryModules using an excessively large map
  src/main/java/org/spongepowered/common/registry/type/world/ChunkRegenerateFlagRegistryModule.java
Labels: type: enhancement, version: 1.12

#2642 Lazy load Advancement textual representation
  src/main/java/org/spongepowered/common/mixin/core/advancements/AdvancementMixin.java
Labels: system: advancement, type: enhancement, version: 1.12

#2645 Fix Forge SOUND_EVENTS registry callback using a phantom reference
  src/main/java/org/spongepowered/common/registry/CommonModuleRegistry.java
Labels: type: bug, version: 1.12

#2649 Fix LaunchProjectileEvent not firing when there are no listeners for SpawnEntityEvent
  src/main/java/org/spongepowered/common/event/tracking/PhaseTracker.java
  src/main/java/org/spongepowered/common/event/tracking/phase/packet/player/InteractionPacketState.java
Labels: system: event, type: bug

#2650 Fix ShouldFire optimization not working for LoadChunkEvent
  src/main/java/org/spongepowered/common/SpongeImpl.java
  src/main/java/org/spongepowered/common/event/SpongeCommonEventHooks.java
  src/main/java/org/spongepowered/common/mixin/core/world/chunk/ChunkMixin.java
Labels: system: event, type: bug

#2651 Fix entity death logging and shouldfire flag for DestructEntityEvent
  src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
Labels: system: event, type: bug

#2646 Fix duplicate empty chunk
  src/main/java/org/spongepowered/common/bridge/world/WorldBridge.java
  src/main/java/org/spongepowered/common/mixin/core/world/WorldMixin.java
  src/main/java/org/spongepowered/common/mixin/core/world/gen/ChunkProviderServerMixin.java
Labels: type: enhancement, version: 1.12

#2654 Don't bypass attackEntityFrom if LivingHurtEvent is cancelled
  src/main/java/org/spongepowered/common/mixin/core/entity/EntityLivingBaseMixin.java
Labels: status: needs testing, system: event, type: bug, version: 1.12

#2652 Fix ParrotDataTest disabling some ShouldFire flags
  testplugins/src/main/java/org/spongepowered/test/ParrotDataTest.java
Labels: system: test, type: enhancement

#2619 Add pathfinding chunkload optimization
  src/main/java/org/spongepowered/common/config/category/OptimizationCategory.java
  src/main/java/org/spongepowered/common/mixin/optimization/pathfinding/PathNavigateMixin_ChunkLoadOptimizations.java
  src/main/java/org/spongepowered/common/mixin/plugin/OptimizationPlugin.java
  src/main/resources/mixins.common.optimization.json
Labels: status: input wanted, type: performance, version: 1.12

#2647 Fix NPE in ManipulatorTest
  src/main/java/org/spongepowered/common/util/Constants.java
Labels: system: test, type: bug

#2644 Cleanup BlockChangeFlagRegistryModule
  src/main/java/org/spongepowered/common/registry/type/world/BlockChangeFlagRegistryModule.java
Labels: type: enhancement, version: 1.12
