Repository SpongePowered/Sponge, pull requests merged in 2020-03, with the labels that each got.

#2514 More core plugin updates
  src/main/java/org/spongepowered/common/SpongeImplHooks.java
  src/main/java/org/spongepowered/common/entity/projectile/ProjectileSourceSerializer.java
  src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
  src/main/java/org/spongepowered/common/mixin/accessor/network/handshake/client/CHandshakePacketAccessor.java
  src/main/java/org/spongepowered/common/mixin/bungee/network/login/ServerLoginNetHandlerMixin_Bungee.java
  src/main/java/org/spongepowered/common/mixin/core/block/NoteBlockMixin.java
  src/main/java/org/spongepowered/common/mixin/core/entity/boss/dragon/EnderDragonEntityMixin.java
  src/main/java/org/spongepowered/common/mixin/core/entity/effect/LightningBoltEntityMixin.java
  src/main/java/org/spongepowered/common/mixin/core/entity/merchant/villager/AbstractVillagerEntityMixin.java
  src/main/java/org/spongepowered/common/mixin/core/entity/merchant/villager/VillagerEntityMixin.java
  src/main/java/org/spongepowered/common/mixin/core/entity/player/PlayerEntityMixin.java
  src/main/java/org/spongepowered/common/mixin/core/entity/projectile/SnowballEntityMixin.java
  src/main/java/org/spongepowered/common/mixin/core/entity/projectile/ThrowableEntityMixin.java
  src/main/java/org/spongepowered/common/mixin/core/entity/projectile/WitherSkullEntityMixin.java
  src/main/java/org/spongepowered/common/mixin/core/item/EnderEyeItemMixin.java
  src/main/java/org/spongepowered/common/mixin/core/network/handshake/ServerHandshakeNetHandlerMixin.java
  src/main/java/org/spongepowered/common/mixin/core/network/login/ServerLoginNetHandlerMixin.java
  src/main/java/org/spongepowered/common/mixin/core/util/ClassInheritanceMultiMapMixin.java
  src/main/java/org/spongepowered/common/mixin/core/util/CooldownTrackerServerMixin.java
  src/main/java/org/spongepowered/common/mixin/core/village/MerchantOfferMixin.java
  src/main/java/org/spongepowered/common/mixin/core/world/RegionMixin.java
  src/main/java/org/spongepowered/common/mixin/core/world/storage/WorldInfoMixin.java
  src/main/java/org/spongepowered/common/network/SpongeNetworkManager.java
  src/main/java/org/spongepowered/common/resourcepack/SpongeResourcePackFactory.java
  src/main/java/org/spongepowered/common/util/metric/SpongeMetricsConfigManager.java
Labels: version: 1.14

#2493 Add missing data to "supplyVanillaManipulators" methods for entities
  src/main/java/org/spongepowered/common/mixin/api/entity/EntityHumanMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/EntityAgeableMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/EntityAreaEffectCloudMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/EntityHangingMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/EntityLivingBaseMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/EntityLivingMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/EntityMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/boss/EntityWitherMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/effect/EntityLightningBoltMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityArmorStandMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityBoatMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityEnderCrystalMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityFallingBlockMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityFireworkRocketMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityItemFrameMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityItemMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityMinecartCommandBlockMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityMinecartContainerMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityMinecartMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityMinecartMobSpawnerMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityMinecartTNTMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityPaintingMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityTNTPrimedMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/item/EntityXPOrbMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/monster/EntityBlazeMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/monster/EntityCreeperMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/monster/EntityEndermanMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/monster/EntityEndermiteMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/monster/EntityIronGolemMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/monster/EntityPigZombieMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/monster/EntityShulkerMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/monster/EntitySlimeMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/monster/EntityVindicatorMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/EntityHorseMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/EntityLlamaMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/EntityOcelotMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/EntityParrotMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/EntityPigMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/EntityRabbitMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/EntitySheepMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/EntityTameableMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/EntityVillagerMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/passive/EntityWolfMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/player/EntityPlayerMPMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/player/EntityPlayerMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/projectile/EntityArrowMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/projectile/EntityFireballMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/projectile/EntityLargeFireballMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/projectile/EntityPotionMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/projectile/EntityShulkerBulletMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/projectile/EntityTippedArrowMixin_API.java
  src/main/java/org/spongepowered/common/mixin/api/mcp/entity/projectile/EntityWitherSkullMixin_API.java
  src/main/resources/mixins.common.api.json
Labels: status: needs review, status: needs testing

#2528 Fix interaction events not being called correctly when left clicking in the air.
  src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
  src/main/java/org/spongepowered/common/mixin/core/network/NetHandlerPlayServerMixin.java
  src/main/java/org/spongepowered/common/mixin/core/server/MinecraftServerMixin.java
  src/main/java/org/spongepowered/common/mixin/core/server/management/PlayerInteractionManagerAccessor.java
  src/main/resources/mixins.common.core.json
Labels: status: needs review, status: needs testing, type: bug
