Repository SpongePowered/Sponge, pull requests merged in 2021-05, with the labels that each got.

#3387 Fix getting the currently active scoreboard for player
  src/mixins/java/org/spongepowered/common/mixin/core/server/level/ServerPlayerMixin.java
Labels: status: needs review, status: needs testing, type: bug, version: 1.16

#3334 Fix player ChangeInventoryEvent.Pickup.Pre
  src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
  src/main/java/org/spongepowered/common/mixin/core/entity/item/EntityItemMixin.java
Labels: status: needs review, status: needs testing, version: 1.12

#3389 Filter degenerate AABBs in World#getIntersectingCollisionBoxes
  src/main/java/org/spongepowered/common/mixin/api/mcp/world/WorldMixin_API.java
Labels: status: needs review, status: needs testing, type: bug, version: 1.12
