Repository SpongePowered/Sponge, pull requests merged in 2021-03, with the labels that each got.

#3313 vanilla: Set up basic integration testing in CI
  .github/workflows/build-project.yaml
  .github/workflows/check-license.yaml
  .github/workflows/deploy.yaml
  .github/workflows/gradle-wrapper-check.yaml
  build.gradle.kts
  vanilla/src/applaunch/java/org/spongepowered/vanilla/applaunch/AppLaunchTargets.java
  vanilla/src/applaunch/java/org/spongepowered/vanilla/applaunch/handler/test/AbstractVanillaTestLaunchHandler.java
  vanilla/src/applaunch/java/org/spongepowered/vanilla/applaunch/handler/test/ClientTestLaunchHandler.java
  vanilla/src/applaunch/java/org/spongepowered/vanilla/applaunch/handler/test/ServerTestLaunchHandler.java
  vanilla/src/applaunch/resources/META-INF/services/cpw.mods.modlauncher.api.ILaunchHandlerService
  vanilla/src/installer/java/org/spongepowered/vanilla/installer/InstallerMain.java
  vanilla/src/installer/java/org/spongepowered/vanilla/installer/InstallerUtils.java
  vanilla/src/installer/java/org/spongepowered/vanilla/installer/LibraryManager.java
  vanilla/src/installer/templates/org/spongepowered/vanilla/installer/Constants.java
  vanilla/src/launch/java/org/spongepowered/vanilla/launch/IntegrationTestLaunch.java
Labels: system: test, type: enhancement, version: 1.16

#3317 Fix deserialization of the name of map decorations
  src/main/java/org/spongepowered/common/map/decoration/SpongeMapDecorationBuilder.java
  testplugins/src/main/java/org/spongepowered/test/map/MapTest.java
Labels: version: 1.16

#3324 Add SpongeKey#defaultValueSupplier for MapValues
  src/main/java/org/spongepowered/common/data/key/SpongeKeyBuilder.java
Labels: system: data, type: bug

#3330 Add support ResourceKey in advancement background
  src/main/java/org/spongepowered/common/advancement/SpongeAdvancementBuilder.java
  src/mixins/java/org/spongepowered/common/mixin/api/mcp/advancements/AdvancementMixin_API.java
  testplugins/src/main/java/org/spongepowered/test/advancement/AdvancementTest.java
Labels: status: needs review, status: needs testing, type: enhancement, version: 1.16

#3318 Add CompletableFutures to Ban/Whitelist Service
  src/main/java/org/spongepowered/common/service/server/ban/SpongeBanService.java
  src/main/java/org/spongepowered/common/service/server/ban/SpongeIPBanList.java
  src/main/java/org/spongepowered/common/service/server/ban/SpongeUserBanList.java
  src/main/java/org/spongepowered/common/service/server/whitelist/SpongeUserWhiteList.java
  src/main/java/org/spongepowered/common/service/server/whitelist/SpongeWhitelistService.java
  src/main/java/org/spongepowered/common/util/UserListUtil.java
  src/mixins/java/org/spongepowered/common/mixin/core/server/players/PlayerListMixin.java
Labels: status: needs review, status: needs testing, type: enhancement, version: 1.16

#3329 Fix SpongeBlockSnapshot#equals
  src/main/java/org/spongepowered/common/block/SpongeBlockSnapshot.java
Labels: status: needs review, status: needs testing, type: bug, version: 1.16
