Repository SpongePowered/Sponge, pull requests merged in 2021-07, with the labels that each got.

#3380 Fix per player scoreboard team friendly fire
  src/mixins/java/org/spongepowered/common/mixin/core/server/level/ServerPlayerMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/world/entity/player/PlayerMixin.java
Labels: status: needs review, status: needs testing, type: bug, version: 1.16

#3439 Another fix of IgniteEntityEvent
  src/mixins/java/org/spongepowered/common/mixin/core/world/entity/EntityMixin.java
Labels: system: event, type: bug, version: 1.16

#3473 add descriptor to distinguish the target method
  src/mixins/java/org/spongepowered/common/mixin/api/minecraft/world/entity/animal/FoxMixin_API.java
  src/mixins/java/org/spongepowered/common/mixin/api/minecraft/world/item/crafting/RecipeManagerMixin_API.java
  src/mixins/java/org/spongepowered/common/mixin/api/minecraft/world/level/saveddata/MapItemSavedDataMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/adventure/bossbar/HackyBossBarPlatformBridgeMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/adventure/text/format/StyleImplMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/commands/CommandsMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/network/protocol/status/ClientboundStatusResponsePacketMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/server/ServerScoreboardMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/server/level/ChunkMapMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/server/level/ServerEntityMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/server/level/ServerPlayerMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/server/network/ServerGamePacketListenerImplMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/server/players/PlayerListMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/world/level/storage/PrimaryLevelDataMixin.java
  src/mixins/java/org/spongepowered/common/mixin/exploit/world/item/WritableBookItemMixin_LimitBookSize.java
  src/mixins/java/org/spongepowered/common/mixin/inventory/event/entity/LivingEntityMixin_Inventory.java
  src/mixins/java/org/spongepowered/common/mixin/ipforward/server/dedicated/DedicatedServerMixin_IpForward.java
  src/mixins/java/org/spongepowered/common/mixin/tracker/server/level/ChunkMapMixin_Tracker.java
Labels: type: enhancement, version: 1.16

#3484 Implement Entity#setPosition and clean up some related logic
  src/main/java/org/spongepowered/common/bridge/server/level/ServerPlayerBridge.java
  src/main/java/org/spongepowered/common/bridge/world/entity/EntityBridge.java
  src/main/java/org/spongepowered/common/bridge/world/level/PlatformServerLevelBridge.java
  src/mixins/java/org/spongepowered/common/mixin/api/minecraft/world/entity/EntityMixin_API.java
  src/mixins/java/org/spongepowered/common/mixin/core/server/level/ServerPlayerMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/world/entity/EntityMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/world/entity/projectile/ThrownEnderpearlMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/world/entity/vehicle/AbstractMinecartContainerMixin.java
  testplugins/src/main/java/org/spongepowered/test/movement/MovementTest.java
Labels: system: entity, type: bug, type: impl request, version: 1.16
