Repository SpongePowered/Sponge, pull requests merged in 2021-06, with the labels that each got.

#3428 Fix error when hooking entity
  src/mixins/java/org/spongepowered/common/mixin/core/world/entity/projectile/FishingHookMixin.java
Labels: type: bug, version: 1.17

#3416 Fix compile errors (incompatible types)
  src/main/java/org/spongepowered/common/mixin/core/entity/EntityMixin.java
Labels: status: needs review, version: 1.12

#3431 Update jansi dep to support ARM64
  gradle.properties
  vanilla/build.gradle.kts
Labels: version: 1.16

#3436 Fix IgniteEntityEvent
  src/mixins/java/org/spongepowered/common/mixin/core/world/entity/EntityMixin.java
  src/mixins/java/org/spongepowered/common/mixin/core/world/entity/player/PlayerMixin.java
Labels: system: event, type: bug, version: 1.16
